### ISSUE TITLE
Which repo?

### ISSUE THREAD

**Issue by samskiter** [TomLXXVI/python-hvac#1]
Hey, I noticed you have a number of repositories with duplicated content - is there any in particular you recommend using/not using?

**Comment by TomLXXVI** [comment]
python-hvac is the most recent repository (package). It is a continuation of the HVAC repository, but python-hvac now uses Poetry for packaging. The goal is to publish python-hvac on PyPi and Conda, when it gets finished and sufficiently documented.

**Comment by samskiter** [comment]
Thanks, happy to help if you need. Currently getting an exception from the
conduit.duplicate method. Deepcopy doesnt like CoolProps Abstract State

**Comment by TomLXXVI** [comment]
Indeed, a TypeError is thrown when calling conduit.duplicate as deepcopy fails on CoolProp's AbstractState. I've modified the duplicate method to work around this issue.

**Comment by samskiter** [comment]
amazing thanks! Just raising another issue - happy to contribute a PR to you
